### PR TITLE
Extract both the left and right values into a tuple of `Option`.

### PR DESCRIPTION
**Pull request by kugland**
```rust
/// Extract both the left and right values into a tuple of [`Option`].
///
/// # Examples
///
/// ```
/// # use either::*;
/// let left: Either<u16, u32> = Left(3u16);
/// assert_eq!(left.into_tuple(), (Some(3u16), None));
/// let right: Either<u16, u32> = Right(7u32);
/// assert_eq!(right.into_tuple(), (None, Some(7u32)));
/// ```
pub fn into_tuple(self) -> (Option<L>, Option<R>) {
    match self {
        Either::Left(l) => (Some(l), None),
        Either::Right(r) => (None, Some(r)),
    }
}
```

### CODE REVIEW

**Comment by cuviper** [comment]
Do you have a real world example where this would be useful? My gut reaction is that this would be more annoying to deal with than just matching the `Either` directly, as now you have to handle impossible `(Some, Some)` and `(None, None)` states.

**Comment by kugland** [comment]
Hello.

Yes, I do.

```
/// This struct is created by the [`Dir::walk()`] method. See its documentation for more.
#[derive(Debug)]
pub struct Walk<'a, T>(Vec<(String, Iter<'a, String, Entry<T>>)>);

impl<'a, T> From<&'a Dir<T>> for Walk<'a, T> {
    fn from(value: &'a Dir<T>) -> Self {
        Self(vec![("".to_owned(), value.children())])
    }
}

impl<'a, T> Iterator for Walk<'a, T> {
    type Item = (String, Option<&'a T>);

    fn next(&mut self) -> Option<(String, Option<&'a T>)> {
        loop {
            let (path, iter) = self.0.last_mut()?;
            if let Some((name, entry)) = iter.next() {
                let path = (path.is_empty())
                    .then(|| name.clone())
                    .unwrap_or_else(|| format!("{path}/{name}"));
                let (children, contents) = (entry.0.as_ref()).either(
                    |v| (Some(v.children()), None),
                    |v| (None, Some(v.contents())),
                );
                if let Some(children) = children {
                    self.0.push((path.clone(), children));
                }
                break Some((path, contents));
            } else {
                self.0.pop();
            }
        }
    }
}
```

**Comment by cuviper** [comment]
There are lots of ways to match that, e.g.:

```rust
if let Left(v) = &entry.0 {
    self.0.push((path.clone(), v.children()));
}
let contents = entry0.as_ref().right().map(File::contents);
```

Or:

```rust
let contents = match &entry.0 {
    Left(v) => {
        self.0.push((path.clone(), v.children()));
        None
    }
    Right(v) => Some(v.contents()),
};
```

**Comment by kugland** [comment]
> There are lots of ways to match that, e.g.:

Yes, certainly. But I think that extracting a tuple of `Option`s, even though it makes impossible
states representable, follows naturally from the idea of the `Either` type, and can potentially
make code more readable.

**Comment by erikjara** [comment]
This operation may resemble the fold method found in Scala's Either type, that allows for a bifurcated processing path: one for success (Right) and one for failure (Left).

This provides more context by Scala's Either type and the purpose of the fold method

> def `fold[C]`(fa: `(A)` => `C`, fb: `(B)` => `C`): `C`
> Applies `fa` if this is a `Left` or `fb` if this is a `Right`.
> 
> | Parameter | Description                              |
> |-----------|------------------------------------------|
> | `fa`      | the function to apply if this is a `Left`|
> | `fb`      | the function to apply if this is a `Right`|
> 
> returns the results of applying the function
> 
> Example:
> ```scala
> val result = util.Try("42".toInt).toEither
> result.fold(
>     e => s"Operation failed with $e",
>     v => s"Operation produced value: $v"
> )

[Documentation](https://www.javadoc.io/doc/io.vavr/vavr/0.9.0/io/vavr/control/Either.html#fold-java.util.function.Function-java.util.function.Function-)

**Comment by erikjara** [comment]
This operation may resemble the fold method found in Scala's Either type, that allows for a bifurcated processing path: one for success (Right) and one for failure (Left).

This allows for the return of a unified type from either branch of execution, with the requirement that the type must be consistent across both the success and failure paths. This includes the possibility of returning an `Option` type, among others.

> def `fold[C]`(fa: `(A)` => `C`, fb: `(B)` => `C`): `C`
> Applies `fa` if this is a `Left` or `fb` if this is a `Right`.
> 
> | Parameter | Description                              |
> |-----------|------------------------------------------|
> | `fa`      | the function to apply if this is a `Left`|
> | `fb`      | the function to apply if this is a `Right`|
> 
> returns the results of applying the function
> 
> Example:
> ```scala
> val result = util.Try("42".toInt).toEither
> result.fold(
>     e => s"Operation failed with $e",
>     v => s"Operation produced value: $v"
> )

[Documentation](https://www.javadoc.io/doc/io.vavr/vavr/0.9.0/io/vavr/control/Either.html#fold-java.util.function.Function-java.util.function.Function-)

**Comment by cuviper** [comment]
@erikjara -- isn't that `fold` the same as [`Either::either`](https://docs.rs/either/latest/either/enum.Either.html#method.either)? I don't see any similarity with splitting into `Option`s.

**Comment by erikjara** [comment]
Ohh, my bad @cuviper, I didn't know about the fold Scala method being similar to Rust's [Either::either](https://docs.rs/either/latest/either/enum.Either.html#method.either) here... So yeah, @kugland could totally use this method for their situation instead of implement a tuple method.

```rust
let (children, contents) = (entry.0.as_ref())
    .map_either(Dir::children, File::contents)
    .either(|left| (Some(left), None), |right| (None, Some(right)))
```

**Comment by cuviper** [comment]
OK -- my opinion is that this isn't a pattern that we should encourage by adding a dedicated method for it, and there are multiple ways to reach that anyway, even if they seem less elegant.

**Pull request closed without merging**
